server:
  port: 8080

spring:
  application:
    name: talktoyou-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/talktotyou
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  devtools:
    restart:
      enabled: true

# JWT 설정
app:
  jwt:
    secret: mySecretKey1234567890123456789012345678901234567890
    expiration: 86400000 # 24시간 (밀리초)

logging:
  level:
    com.talktoyou: DEBUG
    org.springframework.web.socket: DEBUG